# Generated by Django 5.1.1 on 2024-09-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('foiz', models.IntegerField()),
            ],
        ),
    ]
