# Generated by Django 5.1.1 on 2024-09-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_galery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('nomi', models.CharField(max_length=120)),
                ('text', models.TextField()),
            ],
        ),
    ]
