# Generated by Django 5.0.7 on 2024-09-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_complex'),
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deys', models.CharField(max_length=200)),
                ('raqami', models.IntegerField()),
                ('yil', models.CharField(max_length=300)),
                ('yil2', models.CharField(max_length=200)),
                ('raqami2', models.CharField(max_length=200)),
                ('stranasi', models.CharField(max_length=300)),
                ('f_qoshish', models.CharField(max_length=400)),
                ('l_qoshish', models.CharField(max_length=500)),
                ('ochestva_qoshish', models.CharField(max_length=500)),
                ('rojdeniya_qoshish', models.CharField(max_length=500)),
                ('adres_qoshish', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Complex',
        ),
        migrations.DeleteModel(
            name='Exid',
        ),
        migrations.DeleteModel(
            name='Friendly',
        ),
        migrations.DeleteModel(
            name='Galery',
        ),
        migrations.DeleteModel(
            name='Process',
        ),
        migrations.DeleteModel(
            name='Results',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Stay',
        ),
        migrations.DeleteModel(
            name='Works',
        ),
    ]
